//! Bulk-write API — `WriteBatch` for atomic batch commit.
//!
//! Per [ADR-0010](../../../docs/decisions/0010-phase-5-tessera-architecture.md)
//! Decision 3 + Appendix A (Phase 5A Stream A interface contract).
//! `WriteBatch` is the parallel path to [`Cube::write`](crate::Cube::write)
//! for bulk-import workloads. It amortizes the per-cell costs (revision
//! bump, dirty-set update, future listener fire) into a single commit
//! operation, achieving the 10–30× speedup over per-cell writes that
//! ADR-0010 Decision 6 sets WriteBatch performance gates against.
//!
//! See [`docs/specs/engine-semantics.md`](../../../docs/specs/engine-semantics.md)
//! §13 for the per-cell writeback invariants `WriteBatch` preserves
//! across batches; ADR-0010 for the binding interface contract; and
//! [`docs/PERF.md`](../../../docs/PERF.md) §6.16 / §6.17 for the
//! before-and-after measurement story.
//!
//! # Lifecycle
//!
//! ```text
//! new() → push() / push_batch() → commit() → CommitResult
//!                              \         \
//!                               drop      → no-op (staging is pure)
//! ```
//!
//! # Atomicity contract (binding)
//!
//! - `new()` does NOT mutate the cube. No snapshot.
//! - `push()` / `push_batch()` only stage — no cube mutation, no side
//!   effects. Dropping a `WriteBatch` before `commit()` has NO effect.
//! - `commit()` runs in three phases:
//!   1. **Validate** every staged write (permission, cube id, arity,
//!      consolidated, derived, version, lock, type, NaN/Inf). On
//!      validation failure → return `Err`, no snapshot, no mutation.
//!   2. **Snapshot** — capture the pre-commit store immediately before
//!      mutation. Per ADR-0010 Amendment #5 this is at `commit()`
//!      step 2, NOT at `new()`, so dry-run flows that stage but never
//!      commit pay no snapshot cost.
//!   3. **Apply** — single revision bump, write all cells, aggregate
//!      dirty-set update (deduplicating via the bitset's O(1)
//!      `is_dirty`), single (future) listener fire. On any mid-apply
//!      failure the step-2 snapshot is rolled back automatically.
//! - Dropping after successful `commit()` does NOT rollback (commit is
//!   final). Explicit rollback of a committed import is via
//!   `Cube::rollback_to(&snapshot)` against the snapshot returned in
//!   `CommitResult.snapshot_id`.

use crate::coordinate::CellCoordinate;
use crate::cube::Cube;
use crate::error::EngineError;
use crate::id::{PrincipalId, Revision};
use crate::value::ScalarValue;

/// Source identification + audit metadata for a bulk import.
///
/// Per ADR-0010 Appendix A Stream A interface contract.
#[derive(Clone, Debug)]
pub struct WritebackContext {
    /// Human-readable source identifier (e.g., `"hubspot_q3_export.csv"`).
    pub source_name: String,
    /// Unique identifier per logical import. Generated by `mc-tessera`
    /// (Phase 5A Stream D) or the caller. Used as the
    /// `CommitResult.snapshot_id` prefix and as the snapshot label so
    /// future snapshot-registry tooling can recover the pre-commit
    /// snapshot by `import_id`.
    pub import_id: String,
    /// Principal initiating the import. Used for permission checks
    /// during validation and for the
    /// [`Provenance::Input.written_by`](crate::cell::Provenance::Input)
    /// field on every cell written by the batch.
    pub principal: PrincipalId,
}

/// Stages writes for atomic batch commit.
///
/// Borrows the target [`Cube`] exclusively for the lifetime of the
/// batch — only one `WriteBatch` can exist against a given cube at a
/// time, which is the correct single-writer semantic for Phase 5A
/// (per ADR-0010 Decision 11; rayon-based parallelism is gated behind
/// the still-unwritten ADR-0012).
///
/// Per ADR-0010 Appendix A: the `pre_snapshot` store clone is NOT
/// captured at `new()`; it is captured at `commit()` step 2,
/// immediately before mutation. This avoids paying snapshot-clone cost
/// on dry-run flows that stage but never commit (per Amendment #5).
#[derive(Debug)]
pub struct WriteBatch<'cube> {
    cube: &'cube mut Cube,
    context: WritebackContext,
    staged: Vec<(CellCoordinate, ScalarValue)>,
}

/// Summary of a committed batch.
///
/// Per ADR-0010 Decision 3 amendment #3: uses `dirty_count_after`
/// (cumulative) and `newly_dirtied_count` (marginal) as two distinct
/// fields to avoid the Phase 2D `WritebackResult.invalidated`
/// cumulative-vs-marginal ambiguity. Neither field reuses the word
/// "invalidated."
#[derive(Clone, Debug)]
pub struct CommitResult {
    /// Number of cells successfully written by this commit. Equal to
    /// the staged count on success — failed commits return `Err`, not
    /// a partial `CommitResult`.
    pub rows_written: usize,
    /// Number of cells that failed to apply. Always 0 on a successful
    /// commit (the validate-then-apply structure means a returned
    /// `Ok(CommitResult)` has zero failed rows). Reserved for a future
    /// per-row-failure mode that ADR-0010 explicitly chose NOT to
    /// implement in Stream A.
    pub rows_failed: usize,
    /// Cube revision immediately before this commit applied.
    pub revision_before: Revision,
    /// Cube revision immediately after this commit applied. For a
    /// non-empty batch, `revision_after = revision_before.next()` —
    /// every cell written by this batch carries this revision in its
    /// [`StoredCell.revision`](crate::cell::StoredCell). Empty batches
    /// return `revision_after == revision_before` (no bump, no
    /// snapshot, no work).
    pub revision_after: Revision,
    /// Total dirty-set size (cumulative) immediately after this commit.
    /// Useful for diagnostics and dirty-set growth tracking. Per
    /// ADR-0010 Decision 3 amendment #3: this is the cumulative
    /// reading, NOT the marginal one.
    pub dirty_count_after: usize,
    /// Cells that transitioned clean → dirty during this commit.
    /// Marginal semantics — matches the Phase 2D
    /// `WritebackResult.invalidated` shape extended to a batch.
    pub newly_dirtied_count: usize,
    /// Pre-commit snapshot identifier. Format:
    /// `"{import_id}@{revision_before}"`. Phase 5A: this is the
    /// caller-visible handle to the in-memory snapshot rolled back to
    /// on `Cube::rollback_to(&snapshot)`. Phase 5C will add a
    /// snapshot registry indexed by `snapshot_id`.
    pub snapshot_id: String,
}

impl<'cube> WriteBatch<'cube> {
    /// Create a new batch against `cube`. Does NOT mutate the cube.
    /// Per ADR-0010 Amendment #5 no snapshot is captured at this
    /// point; the snapshot is taken at `commit()` step 2 immediately
    /// before mutation.
    pub fn new(cube: &'cube mut Cube, context: WritebackContext) -> Self {
        Self {
            cube,
            context,
            staged: Vec::new(),
        }
    }

    /// Stage a single cell write. Does NOT mutate the cube.
    ///
    /// Per ADR-0010 SPEC QUESTION #7's recommended path: `push()`
    /// performs only the cheap coordinate-arity + cube-id check
    /// (catches obvious caller bugs early). Full validation
    /// (permission, type, derived-cell rejection, lock, NaN/Inf) is
    /// deferred to [`commit()`](Self::commit) step 1, where it can
    /// fail-free without paying any snapshot cost.
    pub fn push(&mut self, coord: CellCoordinate, value: ScalarValue) -> Result<(), EngineError> {
        if coord.cube != self.cube.id {
            return Err(EngineError::Internal(
                "WriteBatch::push: coordinate cube id does not match this batch's cube",
            ));
        }
        if coord.elements().len() != self.cube.dimensions().len() {
            return Err(EngineError::Internal(
                "WriteBatch::push: coordinate arity does not match cube dimension count",
            ));
        }
        self.staged.push((coord, value));
        Ok(())
    }

    /// Stage many cells at once. All-or-nothing on the cheap arity /
    /// cube-id check — if any cell fails, none are added.
    pub fn push_batch(
        &mut self,
        cells: &[(CellCoordinate, ScalarValue)],
    ) -> Result<(), EngineError> {
        let dim_count = self.cube.dimensions().len();
        let cube_id = self.cube.id;
        for (coord, _) in cells {
            if coord.cube != cube_id {
                return Err(EngineError::Internal(
                    "WriteBatch::push_batch: coordinate cube id does not match this batch's cube",
                ));
            }
            if coord.elements().len() != dim_count {
                return Err(EngineError::Internal(
                    "WriteBatch::push_batch: coordinate arity does not match cube dimension count",
                ));
            }
        }
        self.staged.reserve(cells.len());
        for (coord, value) in cells {
            self.staged.push((coord.clone(), value.clone()));
        }
        Ok(())
    }

    /// Number of staged writes.
    pub fn staged_count(&self) -> usize {
        self.staged.len()
    }

    /// Validate → snapshot → apply. Consumes `self`.
    ///
    /// On validation failure (step 1): returns `Err` with no mutation
    /// and no snapshot cost.
    ///
    /// On successful validation: captures a pre-commit snapshot,
    /// applies all writes via the cube's batched fast path, returns
    /// the [`CommitResult`].
    ///
    /// On mid-apply failure (defense-in-depth: validation has already
    /// covered every check that mutates state, but `EngineError::Internal`
    /// from the apply path is still possible): the step-2 snapshot is
    /// restored via `Cube::rollback_to`, and the apply-side error is
    /// propagated.
    pub fn commit(self) -> Result<CommitResult, EngineError> {
        let WriteBatch {
            cube,
            context,
            staged,
        } = self;

        // Phase 5A uses `now_unix_seconds = 0` in WriteBatch by default,
        // matching the determinism convention used throughout the
        // existing test suite (every WritebackRequest in mc-fixtures and
        // the §10 tests uses `now_unix_seconds: 0`). Future Tessera
        // orchestrator (Stream D) can thread a real timestamp through
        // WritebackContext when audit-trail records require wall-clock.
        let now_unix_seconds = 0u64;

        // Per ADR-0010 Decision 3 atomicity contract: validation
        // failure is free. No snapshot, no mutation, just an Err.
        let prepared = cube.batch_validate_all(&staged, context.principal, now_unix_seconds)?;

        // Snapshot id is deterministic in (import_id, revision_before).
        let revision_before = cube.revision();
        let snapshot_id = format!("{}@{}", context.import_id, revision_before.0);

        // Empty-batch fast path: no snapshot, no mutation, no revision
        // bump. Return a CommitResult that reflects the no-op.
        if prepared.is_empty() {
            return Ok(CommitResult {
                rows_written: 0,
                rows_failed: 0,
                revision_before,
                revision_after: revision_before,
                dirty_count_after: cube.dirty().len(),
                newly_dirtied_count: 0,
                snapshot_id,
            });
        }

        // Phase 2: snapshot, per ADR-0010 Amendment #5. The label
        // includes the import_id so a future snapshot-registry tool
        // can recover the snapshot by import_id without a side table.
        let snapshot_label = format!("pre_commit:{}", context.import_id);
        let snapshot = cube.snapshot(Some(&snapshot_label));

        // Phase 3: apply.
        let rows = prepared.len();
        match cube.batch_apply_validated(prepared, context.principal, now_unix_seconds) {
            Ok(outcome) => Ok(CommitResult {
                rows_written: rows,
                rows_failed: 0,
                revision_before: outcome.revision_before,
                revision_after: outcome.revision_after,
                dirty_count_after: outcome.dirty_count_after,
                newly_dirtied_count: outcome.newly_dirtied_count,
                snapshot_id,
            }),
            Err(e) => {
                // Mid-apply failure — rollback to the snapshot
                // captured at step 2. Per spec §19 I-Snap-3 / §16 the
                // rollback bumps the revision and clears dirty
                // (rolled-back state is by definition fresh), so the
                // cube returns to a known-good state. The original
                // apply-side error is what the caller sees.
                cube.rollback_to(&snapshot).ok();
                Err(e)
            }
        }
    }
}
