"""
Reference values for ADR-0033 metrics primitives.
Pinned to the statsmodels / numpy / scipy versions recorded below.
Run: python3 metrics_fixtures.py
Paste the output table into the doc comment at the top of
crates/mc-core/tests/metrics.rs.

DO NOT EDIT INDIVIDUAL VALUES — regenerate the whole table.

Per ADR-0033:
  - Amendment 3: sample variance (ddof=1) — matches numpy/statsmodels default.
  - Decision 2: Wilson 95% CI — formula evaluated on the continuous
    proportion `p` the Rust function receives (avg_over result), NOT on
    a rounded `k = int(p*n)`. statsmodels.proportion_confint is shown
    alongside as a sanity check; the binding reference is the
    closed-form computation against the same `p` the Rust kernel sees.
  - Amendment 7: MLB walk-forward headline parity uses 1e-3 tolerance.
"""
import math

import statsmodels
import numpy as np
import scipy
from statsmodels.stats.proportion import proportion_confint
from scipy.stats import norm

print(f"# Generated by metrics_fixtures.py")
print(
    f"# statsmodels {statsmodels.__version__}; "
    f"numpy {np.__version__}; scipy {scipy.__version__}"
)
print(f"# Wilson 95% — direct closed-form (continuous p) and statsmodels (rounded k).")
print(f"# std/var via numpy with ddof=1 (sample variance per ADR-0033 Amendment 3)")
print()


def wilson_direct(p: float, n: float, alpha: float = 0.05) -> tuple[float, float]:
    """Closed-form Wilson 95% CI on a continuous p. Matches the formula the
    Rust kernel evaluates; statsmodels uses k = int(p*n) which differs at
    the 4th–5th decimal for non-integer p*n."""
    z = norm.ppf(1 - alpha / 2)
    z2 = z * z
    denom = 1 + z2 / n
    center = (p + z2 / (2 * n)) / denom
    margin = z * math.sqrt(p * (1 - p) / n + z2 / (4 * n * n)) / denom
    return (center - margin, center + margin)


# Wilson CI fixtures
print("## Wilson CI fixtures (continuous-p reference — binding for Rust tests)")
print("| p      | n     | lower            | upper            | statsmodels_lo   | note |")
print("|--------|-------|------------------|------------------|------------------|------|")
wilson_cases = [
    (0.5,    100,   "balanced n=100"),
    (0.6,    100,   "moderate edge n=100"),
    (0.5968, 1508,  "MLB walk-forward — V1.0+NB headline (tol 1e-3 vs 0.5718)"),
    (0.0,    100,   "degenerate p=0"),
    (1.0,    100,   "degenerate p=1"),
    (0.5,    1,     "tiny n=1"),
    (0.4,    100,   "for complementary invariant test"),
]
for p, n, note in wilson_cases:
    lo, hi = wilson_direct(p, n)
    k = int(round(p * n))
    sm_lo, _ = proportion_confint(k, n, alpha=0.05, method='wilson')
    print(
        f"| {p:.4f} | {n:>5} | {lo:.9f}      | {hi:.9f}      |"
        f" {sm_lo:.9f}      | {note} |"
    )

# Sample std/var fixtures (ddof=1)
print()
print("## std/var fixtures (sample, ddof=1)")
print("| values                                                   | mean         | std (ddof=1)  | var (ddof=1)  |")
print("|----------------------------------------------------------|--------------|---------------|---------------|")
std_cases = [
    [1.0, 2.0, 3.0, 4.0, 5.0],
    [0.55, 0.62, 0.48, 0.71, 0.53, 0.58],  # MLB-shaped P_Over values
    [0.0, 0.0, 0.0, 0.0, 1.0],             # mostly zeros (sparse)
    [1.0, 1.0, 1.0, 1.0, 1.0],             # all same value
]
for vals in std_cases:
    arr = np.array(vals)
    print(f"| {str(vals):<56} | {arr.mean():.9f}  | {arr.std(ddof=1):.9f}   | {arr.var(ddof=1):.9f}   |")
