//! Tests for Phase 10A evaluation metrics primitives — ADR-0033.
//!
//! Reference values produced by `tests/metrics_fixtures.py` against
//! statsmodels 0.14.6, numpy 2.0.2, and scipy 1.13.1. The script also
//! shows statsmodels' Wilson value for sanity comparison; the binding
//! Rust reference is the closed-form computation against the exact
//! continuous `p` the kernel evaluates (statsmodels' result uses
//! `k = int(round(p*n))` and diverges in the 4th–5th decimal when
//! `p*n` is non-integer).
//!
//! Tolerance:
//!   - 1e-6 for scipy/statsmodels-derived fixtures (the formula is
//!     exact, only floating-point roundoff matters).
//!   - 1e-3 for the MLB walk-forward headline parity test — per
//!     ADR-0033 Amendment 7, the 57.18% claim is reported to four
//!     significant figures, so tighter tolerance would flake.
//!   - 1e-9 for invariant identities (complementary symmetry,
//!     all-same-value variance = 0).
//!
//! Fixture table — regenerated by `python3 tests/metrics_fixtures.py`:
//!
//! ```text
//! # statsmodels 0.14.6; numpy 2.0.2; scipy 1.13.1
//! # Wilson 95% — direct closed-form (continuous p) and statsmodels (rounded k).
//! # std/var via numpy with ddof=1 (sample variance per ADR-0033 Amendment 3)
//!
//! ## Wilson CI fixtures (continuous-p reference — binding for Rust tests)
//! | p      | n     | lower            | upper            | statsmodels_lo   | note |
//! |--------|-------|------------------|------------------|------------------|------|
//! | 0.5000 |   100 | 0.403831530      | 0.596168470      | 0.403831530      | balanced n=100 |
//! | 0.6000 |   100 | 0.502002587      | 0.690598714      | 0.502002587      | moderate edge n=100 |
//! | 0.5968 |  1508 | 0.571825918      | 0.621282161      | 0.571843020      | MLB walk-forward — V1.0+NB headline (tol 1e-3 vs 0.5718) |
//! | 0.0000 |   100 | 0.000000000      | 0.036993498      | 0.000000000      | degenerate p=0 |
//! | 1.0000 |   100 | 0.963006502      | 1.000000000      | 0.963006502      | degenerate p=1 |
//! | 0.5000 |     1 | 0.054620756      | 0.945379244      | 0.000000000      | tiny n=1 |
//! | 0.4000 |   100 | 0.309401286      | 0.497997413      | 0.309401286      | for complementary invariant test |
//!
//! ## std/var fixtures (sample, ddof=1)
//! | values                                                   | mean         | std (ddof=1)  | var (ddof=1)  |
//! |----------------------------------------------------------|--------------|---------------|---------------|
//! | [1.0, 2.0, 3.0, 4.0, 5.0]                                | 3.000000000  | 1.581138830   | 2.500000000   |
//! | [0.55, 0.62, 0.48, 0.71, 0.53, 0.58]                     | 0.578333333  | 0.079854034   | 0.006376667   |
//! | [0.0, 0.0, 0.0, 0.0, 1.0]                                | 0.200000000  | 0.447213595   | 0.200000000   |
//! | [1.0, 1.0, 1.0, 1.0, 1.0]                                | 1.000000000  | 0.000000000   | 0.000000000   |
//! ```

use mc_core::rule::{std_compute, var_compute, wilson_ci_lower_compute, wilson_ci_upper_compute};

const TOL_FIXTURE: f64 = 1e-6;
const TOL_HEADLINE: f64 = 1e-3;
const TOL_INVARIANT: f64 = 1e-9;

// ---------------------------------------------------------------------------
// Wilson CI — Decision 2 + Amendment 7
// ---------------------------------------------------------------------------

#[test]
fn t_wilson_ci_balanced_n100() {
    let lo = wilson_ci_lower_compute(0.5, 100.0).unwrap();
    let hi = wilson_ci_upper_compute(0.5, 100.0).unwrap();
    assert!(
        (lo - 0.403831530).abs() < TOL_FIXTURE,
        "wilson lower(0.5,100): got {lo}"
    );
    assert!(
        (hi - 0.596168470).abs() < TOL_FIXTURE,
        "wilson upper(0.5,100): got {hi}"
    );
}

#[test]
fn t_wilson_ci_moderate_edge_n100() {
    let lo = wilson_ci_lower_compute(0.6, 100.0).unwrap();
    let hi = wilson_ci_upper_compute(0.6, 100.0).unwrap();
    assert!((lo - 0.502002587).abs() < TOL_FIXTURE, "lower: {lo}");
    assert!((hi - 0.690598714).abs() < TOL_FIXTURE, "upper: {hi}");
}

#[test]
fn t_wilson_ci_mlb_walk_forward_headline() {
    // Per Amendment 7: 1e-3 tolerance because the published "57.18%"
    // claim is rounded to 4 significant figures. Tightening would
    // flake against statsmodels (k-rounded) too.
    let lo = wilson_ci_lower_compute(0.5968, 1508.0).unwrap();
    assert!(
        (lo - 0.5718).abs() < TOL_HEADLINE,
        "Wilson LB 57.18% headline parity failed: got {lo}"
    );
}

#[test]
fn t_wilson_ci_complementary_invariant() {
    // wilson_lower(p, n) + wilson_upper(1-p, n) == 1.0 exactly (by
    // formula symmetry — center + margin at p mirrors center - margin
    // at 1-p with the same z and n).
    let lo = wilson_ci_lower_compute(0.4, 100.0).unwrap();
    let hi = wilson_ci_upper_compute(0.6, 100.0).unwrap();
    assert!(
        (lo + hi - 1.0).abs() < TOL_INVARIANT,
        "complementary symmetry: lo({:.6}) + hi({:.6}) = {:.9}",
        lo,
        hi,
        lo + hi
    );
}

#[test]
fn t_wilson_ci_degenerate_p0() {
    // At p=0 the lower bound clamps to 0; the upper is the tight
    // Hanley-McNeil-style "rule of three"-ish bound (~3.69% at n=100).
    let lo = wilson_ci_lower_compute(0.0, 100.0).unwrap();
    let hi = wilson_ci_upper_compute(0.0, 100.0).unwrap();
    assert!(
        (lo - 0.0).abs() < TOL_FIXTURE,
        "p=0 lower should clamp to 0: got {lo}"
    );
    assert!(
        (hi - 0.036993498).abs() < TOL_FIXTURE,
        "p=0 upper: got {hi}"
    );
}

#[test]
fn t_wilson_ci_degenerate_p1() {
    // Symmetric of p=0: lower is non-zero, upper clamps to 1.
    let lo = wilson_ci_lower_compute(1.0, 100.0).unwrap();
    let hi = wilson_ci_upper_compute(1.0, 100.0).unwrap();
    assert!(
        (lo - 0.963006502).abs() < TOL_FIXTURE,
        "p=1 lower: got {lo}"
    );
    assert!(
        (hi - 1.0).abs() < TOL_FIXTURE,
        "p=1 upper should clamp to 1: got {hi}"
    );
}

#[test]
fn t_wilson_ci_tiny_n1() {
    // The closed-form Wilson formula remains well-defined at n=1 even
    // though the binomial interpretation degenerates; statsmodels'
    // rounded-k path gives a different number (k=0 from rounding 0.5).
    // The Rust kernel sees continuous p, so the direct formula wins.
    let lo = wilson_ci_lower_compute(0.5, 1.0).unwrap();
    let hi = wilson_ci_upper_compute(0.5, 1.0).unwrap();
    assert!((lo - 0.054620756).abs() < TOL_FIXTURE, "n=1 lower: {lo}");
    assert!((hi - 0.945379244).abs() < TOL_FIXTURE, "n=1 upper: {hi}");
}

#[test]
fn t_wilson_ci_invalid_returns_none() {
    // All invalid inputs return None at the compute layer — the eval
    // dispatch maps that to ScalarValue::Null per ADR-0031 Amendment 2.
    assert!(wilson_ci_lower_compute(0.5, 0.0).is_none(), "n=0");
    assert!(wilson_ci_lower_compute(0.5, -1.0).is_none(), "n<0");
    assert!(wilson_ci_lower_compute(-0.1, 100.0).is_none(), "p<0");
    assert!(wilson_ci_lower_compute(1.1, 100.0).is_none(), "p>1");
    assert!(wilson_ci_lower_compute(f64::NAN, 100.0).is_none(), "NaN p");
    assert!(wilson_ci_lower_compute(0.5, f64::NAN).is_none(), "NaN n");

    // Same surface for the upper bound.
    assert!(wilson_ci_upper_compute(0.5, 0.0).is_none());
    assert!(wilson_ci_upper_compute(-0.1, 100.0).is_none());
    assert!(wilson_ci_upper_compute(1.1, 100.0).is_none());
    assert!(wilson_ci_upper_compute(f64::NAN, 100.0).is_none());
}

// ---------------------------------------------------------------------------
// var / std — Amendment 3 (sample variance, ddof=1)
// ---------------------------------------------------------------------------

#[test]
fn t_var_sample_default_ddof1() {
    // Per ADR-0033 Amendment 3: sample variance (divide by n-1).
    // numpy.var([1,2,3,4,5], ddof=1) == 2.5 exactly.
    let vals = [1.0, 2.0, 3.0, 4.0, 5.0];
    let v = var_compute(&vals).unwrap();
    assert!(
        (v - 2.5).abs() < TOL_FIXTURE,
        "var(1..=5, ddof=1) = 2.5, got {v}"
    );
}

#[test]
fn t_std_sample_default_ddof1() {
    let vals = [1.0, 2.0, 3.0, 4.0, 5.0];
    let s = std_compute(&vals).unwrap();
    // numpy: 1.5811388300841898
    assert!(
        (s - 1.5811388300841898).abs() < TOL_FIXTURE,
        "std(1..=5, ddof=1): got {s}"
    );
}

#[test]
fn t_var_mlb_shaped_proportions() {
    // Cross-check against the fixture row: [0.55, 0.62, 0.48, 0.71,
    // 0.53, 0.58] → numpy var(ddof=1) = 0.006376667.
    let vals = [0.55, 0.62, 0.48, 0.71, 0.53, 0.58];
    let v = var_compute(&vals).unwrap();
    let s = std_compute(&vals).unwrap();
    assert!((v - 0.006376667).abs() < TOL_FIXTURE, "var: {v}");
    assert!((s - 0.079854034).abs() < TOL_FIXTURE, "std: {s}");
}

#[test]
fn t_var_all_same_value_is_zero() {
    // Per ADR-0033 Decision 3: a constant sample has variance 0. The
    // Welford accumulator returns exactly 0 here (no roundoff because
    // every delta is 0).
    let vals = [1.0, 1.0, 1.0, 1.0, 1.0];
    let v = var_compute(&vals).unwrap();
    assert!(
        v.abs() < TOL_INVARIANT,
        "var of constant sample must be 0: got {v}"
    );
}

#[test]
fn t_var_n_less_than_2_returns_none() {
    // Sample variance is undefined for n<2 — Welford guard returns None.
    // The dispatch maps None → Null per Decision 3.
    assert!(var_compute(&[]).is_none(), "empty");
    assert!(var_compute(&[1.0]).is_none(), "n=1");
    assert!(std_compute(&[]).is_none());
    assert!(std_compute(&[42.0]).is_none());
}

#[test]
fn t_var_skips_nan() {
    // NaN inputs are skipped (matches the `_over` family's skip-Null
    // semantics at the f64 boundary). The remaining 5 non-NaN values
    // are exactly [1,2,3,4,5] → ddof=1 variance = 2.5.
    let vals = [1.0, 2.0, f64::NAN, 3.0, 4.0, 5.0];
    let v = var_compute(&vals).unwrap();
    assert!(
        (v - 2.5).abs() < TOL_FIXTURE,
        "var with NaN skipped: got {v}"
    );
}

#[test]
fn t_var_all_nan_returns_none() {
    // NaNs are skipped; after skipping, k=0 < 2 → None (Null).
    let vals = [f64::NAN, f64::NAN, f64::NAN];
    assert!(var_compute(&vals).is_none(), "all-NaN → None");
    assert!(std_compute(&vals).is_none());
}
