//! Tests for nbinom_sf / nbinom_cdf — Negative Binomial survival function
//! and CDF in mean-dispersion parametrization.
//!
//! Reference values generated by `tests/nbinom_sf_fixtures.py` against
//! scipy 1.13.1. To regenerate the table, run:
//!
//!     python3 crates/mc-core/tests/nbinom_sf_fixtures.py
//!
//! Tolerance: 1e-6 absolute (PMF accumulation regime — wider than the
//! kernel-wide 1e-9 epsilon per ADR-0031 Amendment 1).
//!
//! Fixture grid (pasted verbatim from the script output; do NOT edit
//! individual rows — regenerate the whole table per ADR-0031 Amendment 1):
//!
//! ```text
//! # Generated by nbinom_sf_fixtures.py against scipy 1.13.1
//! # Convention: nbinom_sf(k, mu, alpha) = nbinom.sf(floor(k), n=1/alpha, p=1/(1+alpha*mu))
//!
//! | k     | mu   | alpha | nbinom_sf       | nbinom_cdf      | note |
//! |-------|------|-------|-----------------|-----------------|------|
//! |   8.0 |  8.5 |  0.13 | 0.449201940 | 0.550798060 | MLB typical line, integer |
//! |   8.5 |  8.5 |  0.13 | 0.449201940 | 0.550798060 | Half-integer — equals integer k=8 |
//! |   9.0 |  8.5 |  0.13 | 0.360882026 | 0.639117974 | MLB push-line behavior |
//! |  10.0 |  8.5 |  0.13 | 0.283491963 | 0.716508037 | High line |
//! |  20.0 |  8.5 |  0.13 | 0.010324246 | 0.989675754 | Extreme over (lottery) |
//! |   0.0 |  4.0 |  0.15 | 0.956428740 | 0.043571260 | Low-mu, k=0 (almost always over) |
//! |   4.0 |  4.0 |  0.15 | 0.367553663 | 0.632446337 | At-the-line low-scoring matchup |
//! |   5.5 |  4.0 |  0.15 | 0.244569812 | 0.755430188 | Half-integer over, low-scoring |
//! |   7.5 | 12.0 |   0.1 | 0.806240752 | 0.193759248 | Half-integer under, high-scoring |
//! |  12.5 | 12.0 |   0.1 | 0.418033119 | 0.581966881 | Half-integer over, high-scoring |
//! |  -1.0 |  8.5 |  0.13 | 1.000000000 | 0.000000000 | Negative k -> always over (X >= 0 invariant) |
//! |   8.0 |  8.5 |  0.05 | 0.464321488 | 0.535678512 | Near-Poisson (small alpha) |
//! |   8.0 |  8.5 |   0.3 | 0.425855506 | 0.574144494 | High dispersion |
//! ```

use mc_core::rule::{nbinom_cdf_compute, nbinom_sf_compute};

const TOL: f64 = 1e-6;

/// AC #3 from ADR-0031 Amendment 7: 13 fixture cases pass within 1e-6.
#[test]
fn t_nbinom_sf_fixtures_against_scipy() {
    let cases: [(f64, f64, f64, f64, f64); 13] = [
        (8.0, 8.5, 0.13, 0.449201940, 0.550798060),
        (8.5, 8.5, 0.13, 0.449201940, 0.550798060),
        (9.0, 8.5, 0.13, 0.360882026, 0.639117974),
        (10.0, 8.5, 0.13, 0.283491963, 0.716508037),
        (20.0, 8.5, 0.13, 0.010324246, 0.989675754),
        (0.0, 4.0, 0.15, 0.956428740, 0.043571260),
        (4.0, 4.0, 0.15, 0.367553663, 0.632446337),
        (5.5, 4.0, 0.15, 0.244569812, 0.755430188),
        (7.5, 12.0, 0.10, 0.806240752, 0.193759248),
        (12.5, 12.0, 0.10, 0.418033119, 0.581966881),
        (-1.0, 8.5, 0.13, 1.000000000, 0.000000000),
        (8.0, 8.5, 0.05, 0.464321488, 0.535678512),
        (8.0, 8.5, 0.30, 0.425855506, 0.574144494),
    ];
    for (k, mu, alpha, expected_sf, expected_cdf) in cases {
        let sf = nbinom_sf_compute(k, mu, alpha).expect("valid inputs return Some");
        let cdf = nbinom_cdf_compute(k, mu, alpha).expect("valid inputs return Some");
        assert!(
            (sf - expected_sf).abs() < TOL,
            "nbinom_sf({k}, mu={mu}, alpha={alpha}) = {sf}, expected {expected_sf}"
        );
        assert!(
            (cdf - expected_cdf).abs() < TOL,
            "nbinom_cdf({k}, mu={mu}, alpha={alpha}) = {cdf}, expected {expected_cdf}"
        );
    }
}

/// AC #4 — half-integer floors to integer (load-bearing for MLB lines).
#[test]
fn t_nbinom_sf_half_integer_floor() {
    let a = nbinom_sf_compute(8.5, 8.5, 0.13).unwrap();
    let b = nbinom_sf_compute(8.0, 8.5, 0.13).unwrap();
    let c = nbinom_sf_compute(8.999, 8.5, 0.13).unwrap();
    assert!((a - b).abs() < 1e-9, "8.5 must floor to 8.0: {a} vs {b}");
    assert!(
        (b - c).abs() < 1e-9,
        "8.999 must floor to 8.0 (NOT round): {b} vs {c}"
    );
}

/// AC #5 — integer-line push decomposition: P(over) + P(push) + P(under) = 1.
#[test]
fn t_nbinom_sf_integer_push_line() {
    let sf_9 = nbinom_sf_compute(9.0, 8.5, 0.13).unwrap();
    let cdf_9 = nbinom_cdf_compute(9.0, 8.5, 0.13).unwrap();
    let cdf_8 = nbinom_cdf_compute(8.0, 8.5, 0.13).unwrap();
    let push = cdf_9 - cdf_8;
    let under = cdf_8;
    let over = sf_9;
    assert!(
        (over + push + under - 1.0).abs() < 1e-9,
        "P(over)+P(push)+P(under) must equal 1.0, got {}",
        over + push + under
    );
    assert!(
        push > 0.0 && push < 1.0,
        "push probability must be in (0,1), got {push}"
    );
}

/// AC #6 — sf is non-increasing in k.
#[test]
fn t_nbinom_sf_monotone_decreasing_in_k() {
    let mu = 8.5;
    let alpha = 0.13;
    let mut prev = 1.0;
    for k in 0..=20 {
        let s = nbinom_sf_compute(k as f64, mu, alpha).unwrap();
        assert!(
            s <= prev + 1e-12,
            "sf must be non-increasing in k: sf({k})={s}, sf({})={prev}",
            k - 1
        );
        prev = s;
    }
}

/// AC #7 — sf strictly increases in mu for fixed k (higher predicted mean
/// pushes more mass above the threshold).
#[test]
fn t_nbinom_sf_monotone_increasing_in_mu() {
    let k = 8.0;
    let alpha = 0.13;
    let sf_low = nbinom_sf_compute(k, 4.0, alpha).unwrap();
    let sf_mid = nbinom_sf_compute(k, 8.0, alpha).unwrap();
    let sf_high = nbinom_sf_compute(k, 12.0, alpha).unwrap();
    assert!(
        sf_low < sf_mid,
        "sf({k}, mu=4) < sf({k}, mu=8): {sf_low} vs {sf_mid}"
    );
    assert!(
        sf_mid < sf_high,
        "sf({k}, mu=8) < sf({k}, mu=12): {sf_mid} vs {sf_high}"
    );
}

/// AC #8 — sf + cdf = 1 (shared-helper invariant; cannot drift under Amendment 5).
#[test]
fn t_nbinom_sf_cdf_complement() {
    let cases = [
        (8.0, 8.5, 0.13),
        (10.0, 8.5, 0.13),
        (0.0, 4.0, 0.15),
        (20.0, 8.5, 0.13),
    ];
    for (k, mu, alpha) in cases {
        let sf = nbinom_sf_compute(k, mu, alpha).unwrap();
        let cdf = nbinom_cdf_compute(k, mu, alpha).unwrap();
        assert!(
            (sf + cdf - 1.0).abs() < 1e-9,
            "sf+cdf={} at k={k}, mu={mu}, alpha={alpha}",
            sf + cdf
        );
    }
}

/// AC #9 — invalid-domain inputs return None (mapped to ScalarValue::Null
/// at the dispatch site, per Amendment 2). NEVER NaN. NEVER an error.
#[test]
fn t_nbinom_sf_invalid_returns_null() {
    assert!(
        nbinom_sf_compute(8.0, 0.0, 0.13).is_none(),
        "mu=0 must return None"
    );
    assert!(
        nbinom_sf_compute(8.0, -1.0, 0.13).is_none(),
        "mu<0 must return None"
    );
    assert!(
        nbinom_sf_compute(8.0, 8.5, 0.0).is_none(),
        "alpha=0 must return None"
    );
    assert!(
        nbinom_sf_compute(8.0, 8.5, -0.5).is_none(),
        "alpha<0 must return None"
    );
    assert!(
        nbinom_sf_compute(f64::NAN, 8.5, 0.13).is_none(),
        "NaN k must return None"
    );
    assert!(
        nbinom_sf_compute(8.0, f64::NAN, 0.13).is_none(),
        "NaN mu must return None"
    );
    assert!(
        nbinom_sf_compute(8.0, 8.5, f64::NAN).is_none(),
        "NaN alpha must return None"
    );
    // Same invariants on nbinom_cdf via the shared helper.
    assert!(nbinom_cdf_compute(8.0, 0.0, 0.13).is_none());
    assert!(nbinom_cdf_compute(8.0, 8.5, 0.0).is_none());
    assert!(nbinom_cdf_compute(f64::NAN, 8.5, 0.13).is_none());
}

/// AC #10 — k < 0 returns 1.0 (X is non-negative; threshold below zero is
/// always exceeded). Preserved through the shared cdf(-) = 0 path.
#[test]
fn t_nbinom_sf_negative_k_returns_one() {
    let sf = nbinom_sf_compute(-1.0, 8.5, 0.13).unwrap();
    let cdf = nbinom_cdf_compute(-1.0, 8.5, 0.13).unwrap();
    assert!((sf - 1.0).abs() < 1e-12, "sf(-1) must equal 1.0, got {sf}");
    assert!(
        (cdf - 0.0).abs() < 1e-12,
        "cdf(-1) must equal 0.0, got {cdf}"
    );
    // Larger negative k also returns 1.0.
    assert!((nbinom_sf_compute(-100.0, 8.5, 0.13).unwrap() - 1.0).abs() < 1e-12);
}
