"""
Generator for nbinom_sf / nbinom_cdf reference values (ADR-0031 Amendment 1).

Pinned scipy version (last regenerated against): scipy 1.13.1 (2026-05-27)
Run: python3 nbinom_sf_fixtures.py > fixtures.txt
Then paste the generated Markdown table into the doc comment of
crates/mc-core/tests/nbinom_sf.rs verbatim.

DO NOT edit individual values by hand — regenerate the whole table. If a future
scipy version changes any value beyond 1e-6, surface in chat before silently
adopting the new values (per ADR-0031 Amendment 1).
"""
from scipy.stats import nbinom
import math
import scipy

print(f"# Generated by nbinom_sf_fixtures.py against scipy {scipy.__version__}")
print(f"# Convention: nbinom_sf(k, mu, alpha) = nbinom.sf(floor(k), n=1/alpha, p=1/(1+alpha*mu))")
print()


def sf(k, mu, alpha):
    n = 1.0 / alpha
    p = 1.0 / (1.0 + alpha * mu)
    return float(nbinom.sf(math.floor(k), n, p))


def cdf(k, mu, alpha):
    n = 1.0 / alpha
    p = 1.0 / (1.0 + alpha * mu)
    return float(nbinom.cdf(math.floor(k), n, p))


fixtures = [
    (8.0,   8.5, 0.13, "MLB typical line, integer"),
    (8.5,   8.5, 0.13, "Half-integer — equals integer k=8"),
    (9.0,   8.5, 0.13, "MLB push-line behavior"),
    (10.0,  8.5, 0.13, "High line"),
    (20.0,  8.5, 0.13, "Extreme over (lottery)"),
    (0.0,   4.0, 0.15, "Low-mu, k=0 (almost always over)"),
    (4.0,   4.0, 0.15, "At-the-line low-scoring matchup"),
    (5.5,   4.0, 0.15, "Half-integer over, low-scoring"),
    (7.5,  12.0, 0.10, "Half-integer under, high-scoring"),
    (12.5, 12.0, 0.10, "Half-integer over, high-scoring"),
    (-1.0,  8.5, 0.13, "Negative k -> always over (X >= 0 invariant)"),
    (8.0,   8.5, 0.05, "Near-Poisson (small alpha)"),
    (8.0,   8.5, 0.30, "High dispersion"),
]

print("| k     | mu   | alpha | nbinom_sf       | nbinom_cdf      | note |")
print("|-------|------|-------|-----------------|-----------------|------|")
for k, mu, alpha, note in fixtures:
    print(f"| {k:>5} | {mu:>4} | {alpha:>5} | {sf(k, mu, alpha):.9f} | {cdf(k, mu, alpha):.9f} | {note} |")
